### ISSUE TITLE
v2.0 now incompatible with Unicode rich documents

### ISSUE THREAD

**Issue by kiwi0fruit** [ohanhi/atom-highlight-bad-chars#26]
It would be nice to have a setting to switch to old black-list behaviour.

**Comment by ohanhi** [comment]
You can add whatever characters to the whitelist in the settings, or otherwise revert back to 1.4.1 using `apm install <package_name>@<package_version>`

**Comment by kiwi0fruit** [comment]
I'm aware of this (reverting to 1.4.1 is the best option as whitelisting is
a waste of time). My point was about 2.0+ versions. What's about adding it?

**Comment by ohanhi** [comment]
Can you describe the use case in more detail than just "Unicode rich documents"? Or better yet, can you give an example file? 

The reason I am hesitant to go back right now is that the plugin code got simplified a lot with this [change](https://github.com/ohanhi/atom-highlight-bad-chars/commit/62ef07e434dcd93c3a3fb20dd698f9cc2695aaa7#diff-5eb059f738e1f5f7e178806b320db710), and adding the blacklist mode back would make the plugin work in two entirely different ways depending on the user settings. This means I'd effectively have two plugins to maintain, albeit in one repo.

**Comment by kiwi0fruit** [comment]
* math rich \w+ code that uses Unicode identifiers
* multilanguage Markdown documents. Or simply non-English Markdown
documents.
* non-English comments in code.
* SugarTeX Markdown documents:
https://github.com/kiwi0fruit/sugartex/blob/master/examples/examples.pdf?raw=true

**Comment by ohanhi** [comment]
The non-English languages I was expecting, and I really do think the user whitelist solves this issue. I am a Finnish native speaker myself, so I added `ÅÄÖåäö` to my whitelist. Most other European languages don't commonly use these graphemes, or use e.g. ø or æ instead. I do prefer having these highlighted in my code.

The math symbols I really was not expecting. I wonder how large a user base this affects? Probably not the usual use case, so I think this might merit a separate plugin. Feel free to fork mine from 1.4.1 and publish it! I will even link to it from my readme if you do.

**Comment by kiwi0fruit** [comment]
I guess it's Julia and Python developers. They could do whitelisting of
Greek letters but if it's not done with "make me good" single button then
it's not worth it.

To be honest, I don't believe that the advertised use case of this module
is used by many people: tricks and jokes inside source code is not that
common. I guess the main use case is in Unicode rich documents (or in
strings inside source code). For example: highlight non standard spaces and
hyphens, highlight doppelgangers of ASCII chars (highlighting combining
characters can also be useful but I'm not sure).

Highlighting all non-ascii solves the issue but gives useless distractions
that in my opinion outweight bonuses.

**Comment by olehermanse** [comment]
> I guess it's Julia and Python developers. They could do whitelisting of
Greek letters but if it's not done with "make me good" single button then
it's not worth it.

I'm also a python developer and non-english speaker, and I think the new behavior is much better. Of course I'm not opposed to adding some of the old functionality back as optional settings.

> To be honest, I don't believe that the advertised use case of this module
is used by many people: tricks and jokes inside source code is not that
common. I guess the main use case is in Unicode rich documents (or in
strings inside source code). 

That's not really the advertised use case, and I would be careful about making assumptions like this.
The current implementation is not great for editing rich text documents, but it is (in my opinion) the best approach for plaintext source code. I think Atom and this plugin is mainly used by programmers who write source code (but I could be wrong).

For me this plugin has helped highlight many characters which would otherwise cause hard to debug compiler errors. They are never "jokes". They usually come from people copy-pasting text / source code from PDFs or websites, or unintentionally clicking weird combinations on their keyboard. (alt+space on mac keyboards produces a non-breaking space, and is the most common offender). Sometimes this is in LaTeX code or python code which students send me, they have no idea what is wrong, and this plugin makes it very obvious.

> For example: highlight non standard spaces and
hyphens, highlight doppelgangers of ASCII chars (highlighting combining
characters can also be useful but I'm not sure).

The problem with the previous approach was that there are so many of these ambiguous characters in Unicode, maintaining a list of them is close to impossible. And there are also different opinions about what should be highlighted. #1 #3 #6 #8 #9 #11 #12 #14 #17 #18 #19 #21.

Another advantage of the new approach is that I now know exactly what will be highlighted. It gives much more confidence to know that anything outside of ascii will be highlighted. I no longer have to hunt these symbols down and [open a pull request to add it to the magic list of weird symbols](https://github.com/ohanhi/atom-highlight-bad-chars/pull/19)

> Highlighting all non-ascii solves the issue but gives useless distractions
that in my opinion outweight bonuses.

I completely disagree, but I understand that our use cases are different. Adding an optional list of default math / greek symbols in settings would help you a lot, if I understand correctly.

**Comment by kiwi0fruit** [comment]
Oh, I see. Then the actually interesting symbols are very few: there is
completely no need to highlight all non ASCII: there is only need to keep
track of error giving symbols like you mentioned. I only encountered copy
pasted "" that were autoreplaced to “”. They actually look different but
then «» should also be added. It looks quite different but it can also be
auto-replaced. Same goes for (c) and ©, etc.

So the idea is to slowly add common autoreplacements to the module and this
would solve 99% use cases.

Adding whitelist together with blacklist options would cover the rest 1%. I
am of the opinion that **default** options that should work in 99% use
cases. In 2.0+ the user should tweak options in 50% use cases at least -
it's bad UX in my opinion. So I'll stay on blacklist behavior.

**Comment by kiwi0fruit** [comment]
> The non-English languages I was expecting, and I really do think the user whitelist solves this issue

What shoud chineese user do?

**Comment by olehermanse** [comment]
> So the idea is to slowly add common autoreplacements to the module and this
would solve 99% use cases.

This is what was tried, and it wasn't great. See my comment above.

> Adding whitelist together with blacklist options would cover the rest 1%. I
am of the opinion that **default** options that should work in 99% use
cases. In 2.0+ the user should tweak options in 50% use cases at least -
it's bad UX in my opinion. 

This 99% vs 1% comes from nowhere, you don't know that, stop assuming that the majority is like you.

> So I'll stay on blacklist behavior

Sounds like the best option currently. As the author mentioned, you can also create your own fork of the plugin, or implement the necessary options in a pull request.

> What shoud chineese user do?

Use version 1.4 or implement the necessary settings in a PR or fork.

**Comment by kiwi0fruit** [comment]
\*facepalm\*

**Comment by ohanhi** [comment]
Let's see if other people open issues similar to this one. I can't come up with better ways to gauge the affected user base. If there are a bunch of people who want the old thing back, I will reconsider. For now though, feel free to keep using the previous version or make a fork. 👍

**Comment by kiwi0fruit** [comment]
Forked to [highlight-bad-chars-bl](https://atom.io/packages/highlight-bad-chars-bl) (blacklist). Now it only has the following groups: control chars, whitespace chars, dash/hyphen chars, confusables (few SugarTeX chars and some markdown-it autoreplacements). So it's a reset of confusing chars of some kind.

**Comment by ohanhi** [comment]
Great! I added a note with a link to your package to the bottom of the readme.
